# Dockerfile.prod
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

ENV GRPC_URL=wapi-europe-cafler-logistics-aefpfscuhygqdwgg.francecentral-01.azurewebsites.net:443
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["node", "app.js"]
